// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt6c8B8q2j2DdueiMGdBHagI6ogfo6TD8',
    appId: '1:1010192393434:web:7eb02c483c8a3d06cef1e3',
    messagingSenderId: '1010192393434',
    projectId: 'expense-tracker-c75a3',
    authDomain: 'expense-tracker-c75a3.firebaseapp.com',
    storageBucket: 'expense-tracker-c75a3.firebasestorage.app',
    measurementId: 'G-1MSCZR3PJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZgZPD4k0OPr_o47TD83cRod8qb7F_Ddw',
    appId: '1:1010192393434:android:887e061362d57802cef1e3',
    messagingSenderId: '1010192393434',
    projectId: 'expense-tracker-c75a3',
    storageBucket: 'expense-tracker-c75a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkThQBLV6vDG7sraLQbUXuUpz91qHej3o',
    appId: '1:1010192393434:ios:4e5ed197dd9c09cfcef1e3',
    messagingSenderId: '1010192393434',
    projectId: 'expense-tracker-c75a3',
    storageBucket: 'expense-tracker-c75a3.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt6c8B8q2j2DdueiMGdBHagI6ogfo6TD8',
    appId: '1:1010192393434:web:e9f3e435cca58d6bcef1e3',
    messagingSenderId: '1010192393434',
    projectId: 'expense-tracker-c75a3',
    authDomain: 'expense-tracker-c75a3.firebaseapp.com',
    storageBucket: 'expense-tracker-c75a3.firebasestorage.app',
    measurementId: 'G-95FEW5VKQ0',
  );
}
